DROP DATABASE MAB IF EXISTS;

CREATE DATABASE IF NOT EXISTS MAB;

USE MAB;

CREATE TABLE IF NOT EXISTS Users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(500) DEFAULT NULL,
    lastname VARCHAR(500) DEFAULT NULL,
    phonenumber VARCHAR(500) DEFAULT NULL,
    email VARCHAR(500) DEFAULT NULL,
    company VARCHAR(500) DEFAULT NULL,

    PRIMARY KEY(id)
);